// Author - Heet Punjawat 
// server/DBmodels/GradingSheet.js

const mongoose = require('mongoose');

const gradingCriteriaSchema = new mongoose.Schema({
  // _id of each grading crtieria will be auto-generated by MongoDB
  criteriaName: String,
  points: Number,
  groupCriteria: Boolean,
  individualCriteria: Boolean
});

const gradingSheetSchema = new mongoose.Schema({
  title: String,
  ASUriteId: String,
  StudentName: String,
  gradingCriteria: [gradingCriteriaSchema] // Keeps the grading criteria embedded in the grading sheet
});

module.exports = mongoose.model('GradingSheet', gradingSheetSchema);